In [1]:
import pandas as pd
import sys
sys.path.append('../utils') 
import helper_function as hf

In [4]:
received_df = pd.read_excel('../input/Shipment Tracker.xlsx', sheet_name='Received', header = 1)

In [10]:
require_cols = ['Form Approved Date', 'Form No.', 'L6/L10', 'PO', 'PN', 'QTY', 'UoM',
                'Vendor', 'Buyer', 'Forwarder', 'Way Bill (Tracking#)', 'Air/Ocean/Truck',
                'Incoterm', 'ETDeparture', 'ETArrival', 'Arrive Date', 'GR Date']
received_df = received_df[require_cols]
received_df

,Form Approved Date,Form No.,L6/L10,PO,PN,QTY,UoM,Vendor,Buyer,Forwarder,Way Bill (Tracking#),Air/Ocean/Truck,Incoterm,ETDeparture,ETArrival,Arrive Date,GR Date
0,2024-07-03 00:00:00,752,L6,4370002118,622201V00-024-G,0.2,KPC,PANASONIC,Daniel,FedEx,777186888112,Air,DAP,2024-07-02 00:00:00,2024-07-17 00:00:00,2024-07-08 00:00:00,2024-07-11 00:00:00
1,2024-07-09 00:00:00,NaN,L6,4500037287,1132154,1440,EA,GOOGLE,Danielle,NaN,NaN,NaN,NaN,NaN,NaN,2024-07-11 00:00:00,2024-07-11 00:00:00
2,2024-07-05 00:00:00,NaN,L6,4600001744,880304500-065-G,6000,EA,NaN,Anita,NaN,EI#4840661501,NaN,NaN,NaN,NaN,2024-07-12 00:00:00,2024-07-12 00:00:00
3,2024-07-12 00:00:00,NaN,NaN,4600005896,220107L00-247-G,1785,EA,Lattice,Anita,FEDEX,FEDEX#777111289217,NaN,NaN,NaN,NaN,2024-07-11 00:00:00,2024-07-12 00:00:00
4,7/2/24,765,L6,4600005981,G07138956-1,20,KPC,YAGEO,Bridget,FEDEX,FEDEX # 777209260861,Air,EXW,2024-07-03 00:00:00,2024-07-18 00:00:00,2024-07-11 00:00:00,2024-07-11 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13588,2025-07-02 00:00:00,NaN,L6,4600009425,21050TE00-217-G,12500,EA,WT,Roy,NaN,4675 6640 5218,NaN,NaN,NaN,NaN,2025-06-30 00:00:00,2025-07-02 00:00:00
13589,2025-07-01 00:00:00,3675,L6,4600010674,620130N01-023-G,2000,EA,TAIYO,Esther,Fedex,Fedex 882388448200,,,,2025-07-18 00:00:00,2025-07-01 00:00:00,2025-07-03 00:00:00
13590,2025-07-03 00:00:00,3677,L6,4600009870,320243200-190-G,5000,EA,Arrow,Esther,Fedex,FEDEX#467038551250,NaN,NaN,NaN,2025-07-24 00:00:00,2025-07-07 00:00:00,2025-07-08 00:00:00
13591,2025-07-03 00:00:00,3677,L6,4600010282,32015B400-190-G,52500,EA,Arrow,Esther,Fedex,FEDEX#467038551250,NaN,NaN,NaN,2025-07-24 00:00:00,2025-07-07 00:00:00,2025-07-08 00:00:00
13592,2024-12-11 00:00:00,NaN,L6 - ISSUE,4600006150,1148703-06-613,324,EA,NaN,Daniel,EI,EI#4812771127,NaN,NaN,NaN,2024-12-13 00:00:00,2024-12-13 00:00:00,NaN

In [5]:
tracker_df = pd.read_excel('../input/Shipment Tracker.xlsx', sheet_name='Logistic Shipment Tracker')

In [ ]:
require_cols = ['Shipping form', 'Tracking', 'Incoterm', 'ETD', 'Delivered date', 'Owner', 'Supplier',
                'Buyer', 'Inbound/Outbound', 'Mode', 'Forwarder']
tracker_df.isna().sum()

Shipping form          0
Tracking             273
Incoterm             212
ETD                  443
ETA                  262
Delivered date       506
Delay                268
Shipper Invoice     3349
PO #                3003
Note                3303
Owner                195
Supplier             196
Buyer                199
Inbound/Outbound     199
Mode                 217
Forwarder            463
Custom clear        3435
dtype: int64

In [17]:
tracker_df['PO #'][2830:2880]

2830                  NaN
2831           4500405072
2832           4500400148
2833                  NaN
2834                  NaN
2835                  NaN
2836           4600009839
2837           4500391307
2838                  NaN
2839           4500391307
2840                  NaN
2841                  NaN
2842                  NaN
2843                  NaN
2844           4600009386
2845                  NaN
2846           4600010118
2847           4600009723
2848             Declined
2849           4600010209
2850           4600007870
2851           4600009488
2852             Declined
2853           4500400229
2854      4600008649/9236
2855           4600010119
2856                  NaN
2857                  NaN
2858                  NaN
2859                  NaN
2860                  NaN
2861                  NaN
2862                  NaN
2863                  NaN
2864                  NaN
2865           4505640377
2866           4505640377
2867                  NaN
2868                  NaN
2869                  NaN
2870                  NaN
2871                  NaN
2872                  NaN
2873    4500397399/411159
2874           4505639012
2875           4600010563
2876                  NaN
2877           4600010563
2878           4600009215
2879                  NaN
Name: PO #, dtype: object